[package]
name = "maud"
# When releasing a new version, please update html_root_url in src/lib.rs
version = "0.21.0"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/maud/"
homepage = "https://maud.lambda.xyz/"
repository = "https://github.com/lambda-fairy/maud"
description = "Compile-time HTML templates."
categories = ["template-engine"]
edition = "2018"

[features]
actix-web = ["actix-web-dep", "futures"]

[dependencies]
maud_htmlescape = { version = "0.17.0", path = "../maud_htmlescape" }
maud_macros = { version = "0.21.0", path = "../maud_macros" }
iron = { version = ">= 0.5.1, < 0.7.0", optional = true }
rocket = { version = ">= 0.3, < 0.5", optional = true }
futures = { version = "0.3.0", optional = true }
actix-web-dep = { version = "2.0.0", optional = true, default-features = false, package = "actix-web" }

[dev-dependencies]
compiletest_rs = { version = "0.3.19", features = ["stable"] }

[badges]
travis-ci = { repository = "lambda-fairy/maud" }

[package.metadata.docs.rs]
all-features = true
