[package]
name = "maud"
# When releasing a new version, please update html_root_url in src/lib.rs
version = "0.22.3"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/maud/"
homepage = "https://maud.lambda.xyz/"
repository = "https://github.com/lambda-fairy/maud"
description = "Compile-time HTML templates."
categories = ["template-engine"]
edition = "2018"

[features]
default = []

# Web framework integrations
actix-web = ["actix-web-dep", "futures-util"]

[dependencies]
maud_htmlescape = { version = "0.17.1", path = "../maud_htmlescape" }
maud_macros = { version = "0.22.3", path = "../maud_macros" }
iron = { version = ">= 0.5.1, < 0.7.0", optional = true }
rocket = { version = "0.5.0-rc.1", optional = true }
futures-util = { version = "0.3.0", optional = true, default-features = false }
actix-web-dep = { package = "actix-web", version = ">= 2, < 4", optional = true, default-features = false }
tide = { version = "0.16.0", optional = true, default-features = false }
axum = { version = "0.2", optional = true }

[dev-dependencies]
trybuild = { version = "1.0.33", features = ["diff"] }

[package.metadata.docs.rs]
all-features = true
