[package]

name = "maud"
# When releasing a new version, please update html_root_url in src/lib.rs
version = "0.16.2"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

license = "MIT/Apache-2.0"
documentation = "https://docs.rs/maud/"
homepage = "https://maud.lambda.xyz/"
repository = "https://github.com/lfairy/maud"
description = "Compile-time HTML templates."
categories = ["template-engine"]

[dependencies]
iron = { version = "0.5.1", optional = true }
rocket = { version = ">= 0.1.2, < 0.3", optional = true }

[badges]
travis-ci = { repository = "lfairy/maud" }

[package.metadata.docs.rs]
all-features = true
