[package]

name = "maud"
# When releasing a new version, please update html_root_url in src/lib.rs
version = "0.19.0"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

license = "MIT/Apache-2.0"
documentation = "https://docs.rs/maud/"
homepage = "https://maud.lambda.xyz/"
repository = "https://github.com/lfairy/maud"
description = "Compile-time HTML templates."
categories = ["template-engine"]

[dependencies]
maud_htmlescape = { version = "0.17.0", path = "../maud_htmlescape" }
maud_macros = { version = "0.19.0", path = "../maud_macros" }
iron = { version = ">= 0.5.1, < 0.7.0", optional = true }
rocket = { version = "0.3", optional = true }
actix-web = { version = ">= 0.6.12, < 0.8.0", optional = true }

[dev-dependencies]
compiletest_rs = "0.3.15"

[badges]
travis-ci = { repository = "lfairy/maud" }

[package.metadata.docs.rs]
all-features = true
