[package]

name = "maud_macros"
# When releasing a new version, please update html_root_url in src/lib.rs
version = "0.19.0"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

license = "MIT/Apache-2.0"
documentation = "https://docs.rs/maud_macros/"
homepage = "https://maud.lambda.xyz/"
repository = "https://github.com/lfairy/maud"
description = "Compile-time HTML templates."

[dependencies]
futures = { version = "0.1", optional = true }
literalext = { version = "0.1", default-features = false, features = ["proc-macro"] }
matches = "0.1.6"
maud_htmlescape = { version = "0.17.0", path = "../maud_htmlescape" }

[lib]
name = "maud_macros"
proc-macro = true

[features]
streaming = ["futures"]

[badges]
travis-ci = { repository = "lfairy/maud" }
